name: osam
description: State management library
version: 2.0.1
author: Daniil Surnin <dsrenesanse@gmail.com>
homepage: https://github.com/Renesanse/osam

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  equatable: ^0.6.1
  provider: ^3.1.0+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
