name: osam
description: State management library inspired redux, bloc and SOLID prenciples. It is null safety and very stable
  solution to avoid red screens and bad code.
version: 2.3.0
author: Daniil Surnin <dsrenesanse@gmail.com>
homepage: https://github.com/Renesanse/osam

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  equatable: ^1.0.0
  provider: ^3.1.0+1
  path_provider: ^1.4.4
  hive: ^1.1.1
  hive_flutter: ^0.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
